### ISSUE TITLE
Cannot run commands if installed from github

### ISSUE THREAD

**Issue by dimaqq** [ttag-org/ttag-cli#63]
When `ttag-cli` is installed from a release, commands work correctly:

```
yarn add ttag-cli@1.7.3
...
yarn run ttag update int/en-GB.po src
...
✔ int/en-GB.po updated
```

But if `ttag-cli` is installed from github, commands fail:

```
yarn add https://github.com/ttag-org/ttag-cli
...
yarn run ttag update int/en-GB.po src

internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module '../dist/src/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/dima.tisnek/sugoadmin/node_modules/ttag-cli/bin/ttag:2:1)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
error Command failed with exit code 1.
```

**Comment by AlexMost** [comment]
HI @dimaqq! 
As far as i see, to solve this problem we should commit dist folder to the repository. Do we really need to support this feature? Or is there some other convenient way to solve this issue?

**Comment by dimaqq** [comment]
No, I don't really need this feature. Everything on `ttag-org` is released so frequently, I don't see why anyone would really need to install raw from github 🤔 

A good work-around is `git clone; cd ttag-cli; npm run-script build; npm pack; cp ttag-cli-X.Y.Z.tgz ~/my-app/vendor; cd ~/my-app; yarn add vendor/ttag-cli-X.Y.Z.tgz` 😄
